### ISSUE TITLE
Codename change from magick to heart

### ISSUE THREAD

**Issue by tiagoanleite** [alexAOSP/lineage_device_nokia_magick#2]
As seen in this [early report](https://www.theandroidsoul.com/nokia-heart-specs-release-date/), benchmarks for a Nokia device with the same specs (minus the camera) as the retail Nokia 5 is referred as `heart`, which matches what is reported by this [user over at XDA with his prototype Nokia 5](https://forum.xda-developers.com/nokia-5/how-to/nokia-568-prototype-comparison-t3680842).

Therefore shouldn't de codename be changed from `magick` to `heart` to match the original internal codename from Nokia?

**Comment by alexAOSP** [comment]
Thanks for the tip. I just thought that the codename is TA-1053, but when you build it can not be used. I'll definitely edit it.

**Comment by tiagoanleite** [comment]
My tip was more to avoid any potential confusion because if reckon `magic` was also the codename for an old Qtek/HTC phone I used to have - either the S100 or the S200.

**Comment by tiagoanleite** [comment]
Name updated.

**Comment by HikariCalyx** [comment]
I recommend you to use the codename to "ND1" or "core" instead, since it's the internal codename by FIH.

Nokia 1 - frontier - FRT
Nokia 2 - dynamo - E1M
Nokia 2.1 - dynamo2 - E2M
Nokia 3 - essential - NE1
Nokia 3.1 - essential2 - ES2
Nokia 5 - core - ND1
Nokia 5.1 - core2 - CO2
Nokia 5.1 Plus/X5 - panda - PDA
Nokia 6 - plate - D1C or PLE
Nokia 6.1 - plate2 - PL2
Nokia 6.1 Plus/X6 - dragon - DRG
Nokia 7 - charm - C1N
Nokia 7 Plus - onyx - B2N
Nokia 8 - bang - NB1
Nokia 8 Sirocco - avenger - A1N

Also, I believe Nokia 5 and Nokia 6 shares the same kernel.

**Comment by alexAOSP** [comment]
I see there's a lot of code names on this phone. I think we should go directly to Nokia and ask them because, as I understand, they write differently everywhere. I will correct the exact codename with the next update of the device tree.

**Comment by alexAOSP** [comment]
In build.prop Android 7.1.1 for Nokia 5 i see that "from device/fih/D1C/system.prop".
Codename wiil be is d1c.
